# install.ps1 - one-shot setup for the AMDR publication repository (Windows PowerShell twin of install.sh).
#
# Initializes the two git submodules (vallado, matlab2tikz). The Vallado
# fork is ~237 MB in full (it also carries STK scenario files, C++/Python/
# Fortran/C# ports, and a data library that this pipeline never touches);
# only software/matlab (~2 MB) is needed here, so this script fetches it
# via a partial clone + sparse-checkout instead of a full submodule checkout.
#
# Usage (from the repo root, after `git clone` -- --recursive not required):
#   .\install.ps1

$ErrorActionPreference = "Stop"

if (-not (Test-Path ".gitmodules")) {
    Write-Error "Error: .gitmodules not found. Run this from the repository root."
    exit 1
}

Write-Host "=== AMDR publication - installer ==="
Write-Host ""

# --- Vallado: lean checkout (software/matlab only, ~2 MB of ~237 MB) ---
$valladoMatlabDir = "vallado/software/matlab"
if ((Test-Path $valladoMatlabDir) -and (Get-ChildItem $valladoMatlabDir -ErrorAction SilentlyContinue)) {
    Write-Host "[vallado] already checked out, skipping."
} else {
    Write-Host "[vallado] fetching lean checkout (software/matlab only)..."
    $pinnedLine = git ls-tree HEAD -- vallado
    if (-not $pinnedLine) {
        Write-Error "Error: could not resolve the pinned vallado commit from the superproject."
        exit 1
    }
    $pinnedSha = ($pinnedLine -split '\s+')[2]
    git submodule update --init --no-checkout --filter=blob:none -- vallado
    Push-Location vallado
    try {
        git sparse-checkout init --cone
        git sparse-checkout set software/matlab
        git checkout $pinnedSha
    } finally {
        Pop-Location
    }
    Write-Host "[vallado] done (~2 MB)."
}
Write-Host ""

# --- matlab2tikz: full checkout (small repo, no sparse-checkout needed) ---
if ((Test-Path "matlab2tikz") -and (Get-ChildItem "matlab2tikz" -ErrorAction SilentlyContinue)) {
    Write-Host "[matlab2tikz] already checked out, skipping."
} else {
    Write-Host "[matlab2tikz] fetching..."
    git submodule update --init -- matlab2tikz
    Write-Host "[matlab2tikz] done."
}
Write-Host ""

# --- MATLAB startup helper ---
@'
% Auto-generated by install.ps1 -- adds Vallado + matlab2tikz to the MATLAB path.
addpath(genpath('vallado/software/matlab'));
addpath(genpath('matlab2tikz'));
'@ | Out-File -FilePath "startup.m" -Encoding utf8
Write-Host "Wrote startup.m"
Write-Host ""

Write-Host "=== Install complete ==="
Write-Host "In MATLAB, from this directory, run:"
Write-Host "    startup"
Write-Host "    run_full_pipeline"
