#!/usr/bin/env bash
# install.sh — one-shot setup for the AMDR publication repository.
#
# Initializes the two git submodules (vallado, matlab2tikz). The Vallado
# fork is ~237 MB in full (it also carries STK scenario files, C++/Python/
# Fortran/C# ports, and a data library that this pipeline never touches);
# only software/matlab (~2 MB) is needed here, so this script fetches it
# via a partial clone + sparse-checkout instead of a full submodule checkout.
#
# Usage (from the repo root, after `git clone` — --recursive not required):
#   ./install.sh

set -euo pipefail

if [ ! -f .gitmodules ]; then
    echo "Error: .gitmodules not found. Run this from the repository root." >&2
    exit 1
fi

echo "=== AMDR publication — installer ==="
echo

# --- Vallado: lean checkout (software/matlab only, ~2 MB of ~237 MB) ---
if [ -d vallado/software/matlab ] && [ "$(ls -A vallado/software/matlab 2>/dev/null)" ]; then
    echo "[vallado] already checked out, skipping."
else
    echo "[vallado] fetching lean checkout (software/matlab only)..."
    pinned_sha=$(git ls-tree HEAD -- vallado | awk '{print $3}')
    if [ -z "$pinned_sha" ]; then
        echo "Error: could not resolve the pinned vallado commit from the superproject." >&2
        exit 1
    fi
    git submodule update --init --no-checkout --filter=blob:none -- vallado
    (
        cd vallado
        git sparse-checkout init --cone
        git sparse-checkout set software/matlab
        git checkout "$pinned_sha"
    )
    echo "[vallado] done (~2 MB)."
fi
echo

# --- matlab2tikz: full checkout (small repo, no sparse-checkout needed) ---
if [ -d matlab2tikz ] && [ "$(ls -A matlab2tikz 2>/dev/null)" ]; then
    echo "[matlab2tikz] already checked out, skipping."
else
    echo "[matlab2tikz] fetching..."
    git submodule update --init -- matlab2tikz
    echo "[matlab2tikz] done."
fi
echo

# --- MATLAB startup helper ---
cat > startup.m <<'EOF'
% Auto-generated by install.sh — adds Vallado + matlab2tikz to the MATLAB path.
addpath(genpath('vallado/software/matlab'));
addpath(genpath('matlab2tikz'));
EOF
echo "Wrote startup.m"
echo

echo "=== Install complete ==="
echo "In MATLAB, from this directory, run:"
echo "    startup"
echo "    run_full_pipeline"
